# Generated by Django 4.2.16 on 2024-11-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.CharField(max_length=50)),
                ('ttb', models.CharField(max_length=50)),
                ('tts', models.CharField(max_length=50)),
                ('deal_bas_r', models.CharField(max_length=50)),
                ('cur_nm', models.CharField(max_length=50)),
            ],
        ),
    ]
