# Generated by Django 4.2.16 on 2024-11-19 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0003_answers_saveinvtype_portsavetype_portrisk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portinvtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portrisk',
            name='id',
        ),
        migrations.RemoveField(
            model_name='portsavetype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='saveinvtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='portinvtype',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='portsavetype',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='saveinvtype',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
    ]
