# Generated by Django 4.2.16 on 2024-11-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0003_alter_supportservicelist_selection_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportservicelist',
            name='agency_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='agency_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='agency_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='application_method',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='detail_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='eligibility',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='service_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='service_pur',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='support_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='supportservicelist',
            name='user_class',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
