# Generated by Django 4.2.16 on 2024-11-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0004_alter_supportservicelist_agency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportServiceDetail',
            fields=[
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.supportservicelist')),
                ('document', models.TextField(null=True)),
                ('apply_url', models.URLField(null=True)),
                ('update_date', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
