# Generated by Django 4.2.16 on 2024-11-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0004_remove_portinvtype_id_remove_portrisk_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portinvtype',
            name='alt_invest_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portinvtype',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='portinvtype',
            name='bond_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portinvtype',
            name='dom_stock_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portinvtype',
            name='int_stock_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='high_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='low_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='med_high_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='med_low_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portrisk',
            name='med_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portsavetype',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='portsavetype',
            name='inst_save_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portsavetype',
            name='reg_save_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saveinvtype',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial_products.answers'),
        ),
        migrations.AlterField(
            model_name='saveinvtype',
            name='inv_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saveinvtype',
            name='saving_ratio',
            field=models.FloatField(),
        ),
    ]
