# Generated by Django 4.2.16 on 2024-11-24 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial_products", "0005_supportservicedetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_year", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "남성"), ("female", "여성")], max_length=10
                    ),
                ),
                (
                    "income_level",
                    models.CharField(
                        choices=[
                            ("0-50", "중위소득 0~50%"),
                            ("51-75", "중위소득 51~75%"),
                            ("76-100", "중위소득 76~100%"),
                            ("101-200", "중위소득 101~200%"),
                            ("200+", "중위소득 200% 초과"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_expecting", models.BooleanField(default=False)),
                ("is_pregnant", models.BooleanField(default=False)),
                ("is_birth", models.BooleanField(default=False)),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("farmer", "농업인"),
                            ("fisher", "어업인"),
                            ("livestock", "축산업인"),
                            ("forester", "임업인"),
                            ("employed", "근로자/직장인"),
                            ("unemployed", "구직자/실업자"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "student_status",
                    models.CharField(
                        choices=[
                            ("none", "해당없음"),
                            ("elementary", "초등학생"),
                            ("middle", "중학생"),
                            ("high", "고등학생"),
                            ("college", "대학생/대학원생"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_multicultural", models.BooleanField(default=False)),
                ("is_north_defector", models.BooleanField(default=False)),
                ("is_single_parent", models.BooleanField(default=False)),
                ("is_single_person", models.BooleanField(default=False)),
                ("is_many_children", models.BooleanField(default=False)),
                ("is_no_house", models.BooleanField(default=False)),
                ("is_new_resident", models.BooleanField(default=False)),
                (
                    "business_status",
                    models.CharField(
                        choices=[
                            ("none", "해당없음"),
                            ("prospective", "예비창업자"),
                            ("operating", "영업중"),
                            ("closing", "폐업예정자"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("none", "해당없음"),
                            ("food", "음식점업"),
                            ("manufacturing", "제조업"),
                            ("it", "정보통신업"),
                            ("other", "기타업종"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_disabled", models.BooleanField(default=False)),
                ("is_veteran", models.BooleanField(default=False)),
                ("is_patient", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_male", models.BooleanField(null=True)),
                ("is_female", models.BooleanField(null=True)),
                ("age_start", models.IntegerField(null=True)),
                ("age_end", models.IntegerField(null=True)),
                ("income_0_50", models.BooleanField(default=False)),
                ("income_51_75", models.BooleanField(default=False)),
                ("income_76_100", models.BooleanField(default=False)),
                ("income_101_200", models.BooleanField(default=False)),
                ("income_over_200", models.BooleanField(default=False)),
                ("is_expecting", models.BooleanField(default=False)),
                ("is_pregnant", models.BooleanField(default=False)),
                ("is_birth", models.BooleanField(default=False)),
                ("is_farmer", models.BooleanField(default=False)),
                ("is_fisher", models.BooleanField(default=False)),
                ("is_livestock", models.BooleanField(default=False)),
                ("is_forester", models.BooleanField(default=False)),
                ("is_elementary", models.BooleanField(default=False)),
                ("is_middle", models.BooleanField(default=False)),
                ("is_high", models.BooleanField(default=False)),
                ("is_college", models.BooleanField(default=False)),
                ("is_employed", models.BooleanField(default=False)),
                ("is_unemployed", models.BooleanField(default=False)),
                ("is_multicultural", models.BooleanField(default=False)),
                ("is_north_defector", models.BooleanField(default=False)),
                ("is_single_parent", models.BooleanField(default=False)),
                ("is_single_person", models.BooleanField(default=False)),
                ("is_many_children", models.BooleanField(default=False)),
                ("is_no_house", models.BooleanField(default=False)),
                ("is_new_resident", models.BooleanField(default=False)),
                ("is_extended_family", models.BooleanField(default=False)),
                ("is_prospective", models.BooleanField(default=False)),
                ("is_in_operation", models.BooleanField(default=False)),
                ("is_closing", models.BooleanField(default=False)),
                ("is_food_business", models.BooleanField(default=False)),
                ("is_manufacturing", models.BooleanField(default=False)),
                ("is_other_business", models.BooleanField(default=False)),
                ("is_small_business", models.BooleanField(default=False)),
                ("is_social_welfare", models.BooleanField(default=False)),
                ("is_organization", models.BooleanField(default=False)),
                ("is_corp_manufacturing", models.BooleanField(default=False)),
                ("is_corp_agriculture", models.BooleanField(default=False)),
                ("is_corp_it", models.BooleanField(default=False)),
                ("is_corp_other", models.BooleanField(default=False)),
                ("is_disabled", models.BooleanField(default=False)),
                ("is_veteran", models.BooleanField(default=False)),
                ("is_patient", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_products.supportservicelist",
                    ),
                ),
            ],
        ),
    ]
