# Generated by Django 4.2.16 on 2024-11-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0005_alter_portinvtype_alt_invest_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='q8_average_monthly_income',
        ),
        migrations.AlterField(
            model_name='answers',
            name='q3_income_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q4_emergency_fund_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q5_investment_priority',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q6_safety_or_liquidity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='answers',
            name='q7_household_status',
            field=models.CharField(max_length=100),
        ),
    ]
