# Generated by Django 4.2.16 on 2024-11-20 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_products', '0003_answers_portinvtype_portrisk_portsavetype_and_more'),
        ('financial_products', '0006_remove_answers_q8_average_monthly_income_and_more'),
    ]

    operations = [
    ]
