<template>
    <section class="home-banner">
      <div class="slide-in-bck-center">
        <h1>당신 곁의 금융 매니저, SJ</h1>
        <p>쉽고 친근한 SmartJourney와 함께 스마트한 금융 여정을 시작해 보세요.</p>
      </div>
    </section>
  </template>
  
  <script>
  export default {
    name: "HomeBanner",
  };
  </script>
  
  <style scoped>
 .home-banner {
  background-image: url('@/assets/images/home/home-banner.jpg');
  background-size: cover; /* 이미지 크기를 컨테이너에 맞춤 */
  background-position: center; /* 중앙 정렬 */
  width: 100%; /* 배너가 화면 너비를 차지 */
  height: 100vh; /* 배너 높이를 뷰포트 높이에 맞춤 */
  display: flex;
  flex-direction: column;
  justify-content: flex-start; /*텍스트를 위쪽으로 정렬 */
  align-items: center; /*수평 중앙 정렬 */
  text-align: center;
  color: white;
  padding-top: calc(100vh / 5); /* 화면 높이의 1/3 지점에 위치 */
  font-family: 'Noto Sans KR', sans-serif;
}
  
  .home-banner h1 {
    font-size: 4rem;
    color: #333;
    font-family: 'NanumSquare', sans-serif;
    font-weight: 800
  }
  
  .home-banner p {
    font-size: 2rem;
    color: #666;
    font-family: 'NanumSquare', sans-serif
  }

  .slide-in-bck-center {
	-webkit-animation: slide-in-bck-center 1.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: slide-in-bck-center 1.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2024-11-24 23:13:3
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-bck-center
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-bck-center {
  0% {
    -webkit-transform: translateZ(600px);
            transform: translateZ(600px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes slide-in-bck-center {
  0% {
    -webkit-transform: translateZ(600px);
            transform: translateZ(600px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}

  </style>
  