# Generated by Django 4.2.16 on 2024-11-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('financial_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_products',
            field=models.ManyToManyField(blank=True, related_name='users_with_deposit', to='financial_products.depositproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='saving_products',
            field=models.ManyToManyField(blank=True, related_name='users_with_saving', to='financial_products.savingproducts'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
